from __future__ import annotations

from pathlib import Path

import yaml

from agent.state import AgentState, CycleRecord


def promote_pattern(state: AgentState, record: CycleRecord, review_dir: Path) -> Path | None:
    if not record.hypothesis.novel or record.diff.verdict != "IMPROVED":
        return None
    review_dir.mkdir(parents=True, exist_ok=True)
    path = review_dir / f"{record.hypothesis.id}_{record.target_node}.yaml"
    payload = {
        "id": record.hypothesis.id,
        "name": f"autogenerated_{record.target_node}",
        "trigger": {
            "op_type": next(node.op_type for node in state.current_trace.nodes if node.id == record.target_node),
            "symptoms": [],
            "devices": [state.current_trace.device],
        },
        "root_cause": record.hypothesis.observed_symptom,
        "fix": {
            "description": record.patch.patch_summary,
            "code_template": record.patch.diff_text,
        },
        "validation": {
            "expected_latency_reduction_pct": round(record.diff.target_node_delta_pct, 2),
        },
        "provenance": {
            "author": "agent",
            "validated_on": [state.current_trace.device],
        },
    }
    path.write_text(yaml.safe_dump(payload, sort_keys=False))
    return path
